### ISSUE TITLE
Network Solution Rate 0 Sol/s

### ISSUE THREAD

**Issue by potadibyo** [zelcash/zelcash#11]

**Comment by TheTrunk** [comment]
Hi,
The network solution rate is calculated based on found blocks and time it takes if I recall correctly. Since no block was found, there is no data to calculate the entire network solution rate. 
I suppose that moonroomcash is a fork of zelcash and you are probably having hard time to find a block with a cpu mining as of the target that needs to be satisfied:
https://github.com/zelcash/zelcash/blob/master/src/chainparams.cpp#L90
A lot of usefull information is also shown in debug.log upon starting the daemon with debug flag

**Comment by potadibyo** [comment]
![capture](https://user-images.githubusercontent.com/11804576/46061604-d77df480-c184-11e8-837f-25934d2758c1.PNG)
this is latest snap i took yesterday ,
it shows blockheight 3 
you haved mine 3 blocks
but orphaned 0 block, immature balance : 130000000.00 MRC , mature : 0.00 MRC
